# 주어진 데이터를 가장 잘 설명하는 직선 찾기

https://www.notion.so/sujeen/linear-regression-57302cfbac22470aaca670bb76a9b599?pvs=4

### 경사하강법

In [1]:
import torch
# X = torch.Tensor(2,3)
# X = torch.tensor([[1,2,3],[4,5,6]])

In [2]:
x = torch.tensor(data=[2.0, 3.0], requires_grad=True)
y = x**2
z = 2*y +3


In [3]:
target = torch.tensor([3.0, 4.0])
loss = torch.sum(torch.abs(x-target))
loss.backward()

In [4]:
print(x.grad, y.grad, z.grad)

tensor([-1., -1.]) None None


<ipython-input-4-6c1d48845c75>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(x.grad, y.grad, z.grad)


In [5]:
# 선형회귀분석 모델 만들기
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init

In [6]:
num_data = 1000
num_epoch = 500


In [7]:
x = init.uniform_(torch.Tensor(num_data, 1), -10, 10)
noise = init.normal_(torch.FloatTensor(num_data, 1), std=1)
y = 2*x +3
y_noise = y+noise

In [8]:
model = nn.Linear(1,1)
loss_func = nn.L1Loss()

In [9]:
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [10]:
label = y_noise
for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(x)

    loss = loss_func(output,label)
    loss.backward()
    optimizer.step()

    if i % 10 == 0:
        print(loss.data)



tensor(6.1373)
tensor(3.7042)
tensor(2.2634)
tensor(2.0279)
tensor(1.9279)
tensor(1.8390)
tensor(1.7557)
tensor(1.6759)
tensor(1.6003)
tensor(1.5282)
tensor(1.4585)
tensor(1.3913)
tensor(1.3293)
tensor(1.2717)
tensor(1.2198)
tensor(1.1735)
tensor(1.1323)
tensor(1.0946)
tensor(1.0613)
tensor(1.0315)
tensor(1.0044)
tensor(0.9797)
tensor(0.9575)
tensor(0.9381)
tensor(0.9211)
tensor(0.9061)
tensor(0.8927)
tensor(0.8808)
tensor(0.8703)
tensor(0.8614)
tensor(0.8540)
tensor(0.8476)
tensor(0.8424)
tensor(0.8379)
tensor(0.8339)
tensor(0.8305)
tensor(0.8273)
tensor(0.8246)
tensor(0.8222)
tensor(0.8203)
tensor(0.8185)
tensor(0.8170)
tensor(0.8156)
tensor(0.8146)
tensor(0.8137)
tensor(0.8130)
tensor(0.8123)
tensor(0.8117)
tensor(0.8112)
tensor(0.8107)


In [13]:
param_list = list(model.parameters())
print("param:", param_list)
print("w:", param_list[0], "b:", param_list[1])

param: [Parameter containing:
tensor([[1.9984]], requires_grad=True), Parameter containing:
tensor([2.9793], requires_grad=True)]
w: Parameter containing:
tensor([[1.9984]], requires_grad=True) b: Parameter containing:
tensor([2.9793], requires_grad=True)


In [14]:
print(param_list[0].item(), param_list[1].item())

1.9984488487243652 2.9793083667755127
